name: GAIA v6.7 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: python gaia_v67.py --mode test

    - name: Run benchmark
      run: python gaia_v67.py --mode benchmark --cycles 500

    - name: Save benchmark results
      run: |
        mkdir -p artifacts
        python gaia_v67.py --mode benchmark --cycles 1000 > artifacts/benchmark.txt
      continue-on-error: true

    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: gaia-benchmarks
        path: artifacts/