name: CI Tests and Benchmarks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping dependency installation."
          fi
      - name: Run validation
        run: python3 gaia_v67.py --mode test > results.json
      - uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: results.json

  benchmark:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt file found. Skipping dependency installation."
          fi
      - name: Run benchmark
        run: python3 gaia_v67.py --mode benchmark --cycles 1000 > benchmark.json
      - uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: benchmark.json